StudentEnrollTrackHamlin: StudentEnrollTrackHamlin.cpp
	g++ -g -ggdb -Wpedantic -Wall -Wextra -Werror -Wshadow -Wunreachable-code --std=c++20 -o StudentEnrollTrackHamlin.exe StudentEnrollTrackHamlin.cpp

tmp: tmp.cpp
	g++ -g -ggdb -Wpedantic -Wall -Wextra -Werror -Wshadow -Wunreachable-code --std=c++20 -o tmp.exe tmp.cpp